export const Base = [
    {
      id: "1",
      Category:"Adult",
      Engine: "100 cm3",
      Manufacter: "Mercedes",
      Gearsbox: "Manual",
      Karting:"Mercedes W-14",
      price:"150 $",
      img:"https://media.istockphoto.com/id/1383038111/photo/racing-kart-without-pilot-isolated-on-white-background-karting-concept-for-design-racing.jpg?s=612x612&w=0&k=20&c=d4Lp4AcQTQ-UmfIb4NZvTYiA2QWCqREIA8l38o-wR78="
       
    },
    {
        id: "11",
        Category:"Adult",
        Engine: "125 cm3",
        Manufacter: "Redbull",
        Gearsbox: "Automatique",
        Karting:"Redbull RB-17",
        price:"300 $",
        img: "https://media.istockphoto.com/id/509793078/photo/go-kart.jpg?s=612x612&w=0&k=20&c=pwPDp50SCpcoE4Oh5SmyzZhsvTsaxMuoLE2BcUVnWtA=",  
    },
    {
        id: "2",
        Category:"Adult",
        Engine: "100 cm3",
        Manufacter: "Ferrari",
        Gearsbox: "Automatique",
        Karting:"Ferrari SF-23",
        price:"220 $",
        img: "https://media.istockphoto.com/id/139388023/photo/card.jpg?s=612x612&w=0&k=20&c=sOOAJM11bPT92shUnFlDO5pPMYpIBc3jjqE2XrVs4Kg=",  
    },
    {
        id: "3",
        Category:"Adult",
        Engine: "175 cm3",
        Manufacter: "Alpine",
        Gearsbox: "Automatique",
        Karting:"Alpine	A523",
        price:"230 $",
        img: "https://media.istockphoto.com/id/179285476/photo/card.jpg?s=612x612&w=0&k=20&c=NQfl_UkYo_xKMZFey3SGz_JSJNTCjWcNK7eb0ODzPiE=",  
    },
    {
        id: "4",
        Category:"Adult",
        Engine: "175 cm3",
        Manufacter: "McLaren",
        Gearsbox: "Hybride",
        Karting:"McLaren MCL60 ",
        price:"100 $",
        img: "https://media.istockphoto.com/id/453999351/photo/go-kart.jpg?s=612x612&w=0&k=20&c=yrj8z8k9BWdEB0it8fbo2AIW80hs8OCG72FrPdiJkFg=",  
    },
    {
        id: "5",
        Category:"Adult",
        Engine: "175 cm3",
        Manufacter: "Alfa Roméo",
        Gearsbox: "Manual",
        Karting:"Alfa Romeo C43",
        price:"180 $",
        img: "https://media.istockphoto.com/id/149867272/photo/go-kart-racer-speeding-around-track.jpg?s=612x612&w=0&k=20&c=J8TwJ__AYMUPOjhZDpGB1hdTgcaeq_TNrd1yl1kN3BM=",  
    },
    {
        id: "6",
        Category:"Adult",
        Engine: "200 cm3",
        Manufacter: "Aston Martin",
        Gearsbox: "Manual",
        Karting:"Aston Martin AMR23",
        price:"180 $",
        img: "https://media.istockphoto.com/id/1409218827/photo/karting-machine-vehicle-parked-near-racetrack-go-kart-hobby.jpg?s=612x612&w=0&k=20&c=LEojAWyvw3i4QUu5RuDtTtepLjCalJNfbWYmJXwyb7A=",  
    },
    {
        id: "7",
        Category:"Child",
        Engine: "250 cm3",
        Manufacter: "AlphaTauri",
        Gearsbox: "Manual",
        Karting:"AlphaTauri AT04 ",
        price:"180 $",
        img: "https://media.istockphoto.com/id/173690954/photo/kart-in-action.jpg?s=612x612&w=0&k=20&c=WOsJ9FH7ZvVkM9RnWtZFDty8CD7Lf4dWDH9byIKy16M=",  
    },
    {
        id: "8",
        Category:"Child",
        Engine: "250 cm3",
        Manufacter: "Williams",
        Gearsbox: "Automatique",
        Karting:"Williams FW45 ",
        price:"250 $",
        img: "https://media.istockphoto.com/id/180895110/photo/go-cards.jpg?s=612x612&w=0&k=20&c=PZj0H8I_nh-DuUXhQF6-9N4PKevdPTYOyWmUG9mJYkg=",  
    },
    {
        id: "9",
        Category:"Child",
        Engine: "250 cm3",
        Manufacter: "Andretti",
        Gearsbox: "Automatique",
        Karting:"Andretti FD-50",
        price:"275 $",
        img: "https://media.istockphoto.com/id/544579310/photo/the-racing-card.jpg?s=612x612&w=0&k=20&c=Ch1cRTOcvSUJLHw6jlpIWYxQ7Q3Tte7VvMz2ZPGd5pY=",  
    },
    {
        id: "10",
        Category:"Child",
        Engine: "125 cm3",
        Manufacter: "Haas",
        Gearsbox: "Manual",
        Karting:"Haas VF-23 ",
        price:"150 $",
        img: "https://media.istockphoto.com/id/172318354/photo/two-people-with-helmets-racing-go-carts-around-a-track.jpg?s=612x612&w=0&k=20&c=FgO4I38yvloZLwf_O4OSac5nSxiUnFeqFaXZeen43Lk=",  
    },
    
    {
        id: "12",
        Category:"Child",
        Engine: "125 cm3",
        Manufacter: "Porshe",
        Gearsbox: "Manual",
        Karting:"Porshe ca-001",
        price:"245 $",
        img: "https://media.istockphoto.com/id/526931739/photo/go-carting.jpg?s=612x612&w=0&k=20&c=8rVk_ugf6j2HPbdZXezb9P4MjKNO7LZ2PRCNHP3bBv0=", 
    },
    {
        id: "13",
        Category:"Adult",
        Engine: "300 cm3",
        Manufacter: "Redbull",
        Gearsbox: "Automatique",
        Karting:"RedBull RB19 ",
        price:"285 $",
        img: "https://media.istockphoto.com/id/172175004/photo/a-go-kart-and-driver-racing-round-a-track.jpg?s=612x612&w=0&k=20&c=93q5vs4etilfue49Qr8oRzAPkXwFMttzenx_Znu798Q=",  
    },
    {
        id: "14",
        Category:"Adult",
        Engine: "300 cm3",
        Manufacter: "Mercedes",
        Gearsbox: "Automatique",
        Karting:"Mercedes W11 ",
        price:"300 $",
        img: "https://media.istockphoto.com/id/172194430/photo/kart-in-action.jpg?s=612x612&w=0&k=20&c=LZtOadxOtBtuZXeC6r1tS_LCJ4h5kJVQTC3oPzeG7cM=",  
    },


];
